import "dotenv/config";
import db from "@/infrastructure/db";
import { eventName } from "@/infrastructure/db/schema/auth.schema";

async function seedEvents() {
    const events = [
        { title: "Pre-Convention" },
        { title: "Main Event Day 1" },
        { title: "Main Event Day 2" },
        { title: "Main Event Day 3" },
        { title: "The Important Role Psychologists Play in Sports" },
        { title: "Assessment of Personality Styles and Disorders" },
        { title: "Deliberate Practice for Counselors" },
        { title: "Mapping Practices" },
        { title: "Pioneering Progress: Innovations in Elderly Mental Health Care for Aging Filipinos" },
        { title: "The Value of Qualitative Findings in the Practice of Psychology" },
        { title: "Why Academic Resilience Matters in the Context of Climate Change?" },
        { title: "Interventions for Psychology in Health and Wellbeing: From Traditional to Modern" },
        { title: "Vulnerable Communities Focus" },
        { title: "Substance Use Prevention and Rehabilitation in the Philippines: Approaches, Evidences and Narratives" },
        { title: "Psychological Landscape in Sports and Movement Exploring Anxiety, Motivation and Mental Health" },
        { title: "Queer Justice and Advocacy in the Philippines" },
        { title: "Navigating Filipino Work Realities: Leadership, Team Development, and Indigenous HR Practices" },
        { title: "Wellbeing and Mental Health in Higher Education Frameworks, Protocols, and Best Practices" },
        { title: "Culturally Responsive Mindfulness BaseD-Program Initial Outcomes and Evidence of Feasibilty and Acceptability" },
        { title: "Psychological Practice in Social Welfare" },
        { title: "The Global Context of Psychology and Human Rights" },
        { title: "Human Sustainability at Work: Mental Health, Organizational Culture, and Employee Engagement" },
        { title: "Beyond PFA: Exploring Best Practices outside of Psychological First Aid" },
        { title: "GenAI in the Conduct of Psychological Assessment" },
        { title: "Ethical Decision-Making Process" },
        { title: "Technology's Impact on Psychology" },
        { title: "Psychological Responses to Climate Crisis" },
        { title: "Struggles and Strength Stories of Hope, Healing and Well-being" },
        { title: "Pathways to Education, Prosociality, and Youth Participation" },
        { title: "Reimagining Pedagogical Futures: Innovations, Ethics, and AI in Psychology Learning and Teaching" },
        { title: "Care and Connection in Neurodiverse Realities: Filipino Narratives of Resilience, Rights, and Relationships" },
        { title: "Experiences in Sports: Perspectives on Participation, Resilence, Rights and Relationships" },
        { title: "Intersecting Minds: Cultural and Clinical Perspectives on Body Dysmorphic and Obsessive Compulsive Disorders in Southeast Asia" },
        { title: "Chapter Meetings" },
        { title: "Towards Inclusive Education: Facilitators, Barriers, and Insights from Higher Education Teachers" },
        { title: "Strength-Based Approach in Assessment: Integration and Practice Considerations" },
        { title: "Institutionalizing Gender-Inclusive Practices in HEIs: The Story of the Ateneo Gender Hub" },
        { title: "Psychological Practice in Family Court Civil Cases" },
        { title: "Ugnayan: Applying Social Psychology to Advocacy Work and Community Action" },
        { title: "APA Panel" },
        { title: "Regional Roots, Global Goals: Psychology in Action for Health, Education, Inclusion and Resilience" },
        { title: "A Community that Cares: Task Shifting Mental Health Initiatives in Underserved Settings" },
        { title: "Approaches in Learning and Cognitive Development of Children and Adults" },
        { title: "Counseling Psychology and Clinical Governance: Latest Trends in Client Needs, Systems, and Professional Care" },
        { title: "Effectiveness and Impact of Interventions" },
        { title: "From Pathogenesis to Recovery: Exploring the Spectrum of Mental Health Disorders" },
        { title: "Resilience and Well-being in Northern Mindanao: Key Features and Implications to Mental Health Intervention" },
        { title: "Queering and Decolonizing Psychology in Asia" },
        { title: "Practicing Nature-based Therapy as a Psychotherapeutic Approach and a Pathway toward Environmental Action" },
        { title: "Fifty Minutes to Change: Crafting a CBT Session That Works" },
        { title: "Centering the Learner, Centering the World: Psychological Literacy and Competency-Based Psychology Education" },
        { title: "Reimagining Research: A Brief Introduction to Feminist Research Practices in Psychology" },
        { title: "Bazinga! Why Your Feelings Know Things Before You Do" },
        { title: "Strengthening Coaching and Supervision in Community-Based Drug Rehabilitation Programs" },
        { title: "Psychological Testiing and Assessment in the Philippines" },
        { title: "Multilayered Political Psychology for Sustainable Peace" },
        { title: "NGO and Community Transformation in the Philippines" },
        { title: "Psychology at the Forefront of Public Health" },
        { title: "Best Practices in Clinical Supervision" },
        { title: "Transformative Narrative of Empowered and Extraordinary Filipino Women" },
        { title: "Achieving Learning Competencies and Sound Psychological Wellbeing" },
        { title: "Instruction, Support, and Beliefs in Southeast Asian Math Engagement" },
        { title: "Psychologists as Expert Witnesses" },
        { title: "A Quick Look at A Quick Look at Neurolinguistic Programming (NLP)" },
        { title: "Disaster Situations: Psychological Practice and Response" },
        { title: "The Psychology of Injury and Rehabilitation: Supporting Mental and Emotional Recovery" },
        { title: "Introduction to Global and Public Mental Health: Critical Perspectives, Local Realities, and Sustainable Future" },
        { title: "Meaning-Making of Caregivers of Neurodivergents" },
        { title: "Issues in Lifespan Development Across Contexts" },
        { title: "Psychological Insights to Engage Minds and the Future" },
        { title: "Strengthening Meaning, Wellbeing and Workplace Mental Health in the Filipino Context" },
        { title: "From Fear to Flourishing Understanding Hope, Compassion, and Mental Health in Youth" },
        { title: "Queer Lives Across the Lifespan" },
        { title: "Adventure in Marriage and Family Therapy: Concurrent Individual and Relational Therapeutic Work Experience in the Philippines" },
        { title: "Cultural Values, Social Action, and Transnational Solidarity" },
        { title: "Resilient Psychology for Equitable Futures in Work, Technology, and Urban Communities" },
        { title: "Healing in Nature: Forest Therapy for LGBTQ+ Mental Health and Well-Being" },
        { title: "Rejuvenating the Soul in the Study of Psychology" },
        { title: "Healthy Behaviours in Chronic Illness" },
        { title: "Contemporary Tends in Clinical Practice: Reflections on my Journey from Interpretation to Experience" },
        { title: "SIG Meetings" },
        { title: "The Future of Psychology in a VUCA World" },
        { title: "Strengthening Personal Resilience – Coping with Workplace Bullying" },
        { title: "Promoting Trauma Recovery in Residential Care: A Singaporean Perspective" },
        { title: "Change and Catastrophe: Gendered Impacts of the Lahaina Wildfire on Filipino Women" },
        { title: "Psych CHED Techinical Panel Consultative Meeting" },
        { title: "Trauma Recovery, Parental Support, and Youth Mental Health: Community-Based Interventions Across Southeast Asia" },
        { title: "Work, Culture, and Mental Health: Understanding Human Behavior in Diverse Contexts" },
        { title: "Division Meeting" },

    ];

    await db.insert(eventName).values(events);
    console.log("Seeded event_name table with events.");
}

seedEvents().catch((err) => {
    console.error(err);
    process.exit(1);
});
