name: Build Application

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build
        env:
          DB_URL: postgres://user:pass@localhost:5432/testdb
          BETTER_AUTH_SECRET: dummy
          BETTER_AUTH_URL: http://localhost:3000
          NEXT_PUBLIC_BASE_URL: http://localhost:3000
          REDIS_URL: redis://localhost:6379
          RESEND_API_KEY: dummy
          RESEND_FROM_EMAIL: dummy@gmail.com